#create by winton wang
version: '3.6'
services:
# 定义的服务
  web:
    image: nginx:1.16
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./www:/www
      - ./nginx:/etc/nginx
  php:
    build: 
      context: ./php
    image: php-fpm:7.3
    container_name: php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./www:/www
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: >
          bash -c "
          chmod 644 /etc/mysql/conf.d/*.cnf
          && /entrypoint.sh mysqld
          "
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/log:/mysql/log
  redis:
    image: redis:5.0
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    volumes:
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/data:/data
  # swoole:
  #   build: 
  #     context: ./swoole
  #   image: php-swoole:7.4-4.5.11
  #   container_name: swoole
  #   restart: always
  #   ports:
  #     - 9501:9501
  #   volumes:
  #     - ./www:/www
  #   #覆盖镜像最后的启动命令 使用：php -e 启动会慢很多但是可以yasd调试
  #   command: php -e /www/hyperf/bin/hyperf.php start
  #   environment:
  #     - PHP_IDE_CONFIG=serverName=yasd