#create by winton wang
version: '3.6'
services:
# 定义的服务
  web:
    image: nginx:1.16
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx:/etc/nginx
  php:
    build: 
      context: ./php
    image: php:7.3-fpm
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./www:/usr/share/nginx/html
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
  redis:
    image: redis:5.0
    container_name: redis-server
    ports:
      - 6379:6379
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    volumes:
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/data:/data
