#create by winton wang
version: '2'
services:
# 定义的服务
  web:
    image: nginx:1.12
    container_name: nginx
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - php
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
  php:
    build: 
      context: ./php
      dockerfile: php-fpm
      args:
        version: 7.1-fpm
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./www:/usr/share/nginx/html
  db:
    image: mariadb:10.2
    container_name: mariadb
    ports:
      - 3306:3306
    # privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mariadb:/var/lib/mysql
